version: '3.9'

services:
  frontend:
    build:
      context: ./frontendpnc
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5100:5173"
    volumes:
      - ./frontendpnc:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true